name: "Publish Immutable Action Version"

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      attestations: write 
      id-token: write
      packages: write
      actions: read 
    steps:
    - name: Checking out
      uses: actions/checkout@v4
    - name: Publish
      id: publish
      uses: actions/publish-immutable-action@main 
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
